### PR TITLE
make old lava scale to texture sizes of lava from resource packs

### PR DESCRIPTION
**Pull request by forkiesassds**

### CODE REVIEW

**Comment by SFort** [comment]
on a x256 texture pack it looks like the following screenshot and drops the fps from 120 to 20
screenshot
i don't understand why you'd want this.
is it intentional, does it look good with a specific texture pack resolution?

**Comment by forkiesassds** [comment]
> on a x256 texture pack it looks like the following screenshot and drops the fps from 120 to 20 screenshot i don't understand why you'd want this. is it intentional, does it look good with a specific texture pack resolution?

IIRC MCPatcher also used to do something similar to this, I understand the point of keeping it 16x for performance reasons.

**Comment by exaskye** [comment]
It is technically more correct, at least to MCPatcher/old-OptiFine behavior, but I intentionally left this out when making the port as it never really looks good. The original behavior is an artifact of the fact all blocks used to be on the terrain.png and had to have matching resolutions. MCPatcher simply made the textures match the current atlas size as a quick fix.

If we're gonna add this, I feel it needs to be a separate option. It's a performance concern and subject to opinion.

**Comment by forkiesassds** [comment]
> If we're gonna add this, I feel it needs to be a separate option. It's a performance concern and subject to opinion.

I'm not sure how to do sub-options for a tweak like that.

**Comment by exaskye** [comment]
You can see an instance of this for Feather Falling V and Observers See Entities — it's just a second feature flag that has a name starting with the thing it's a child of.

It's messy but it's what we got.

**Pull request merged**
