### PR TITLE
Add Underwater Explosions

### PR DESCRIPTION
**Pull request by SFort**

### CODE REVIEW

**Review by exaskye — APPROVED** [review]
This is a good way to do this.

**Comment by exaskye** [comment]
Just noticed the features.txt changes are indented with spaces; this doesn't work. The format *requires* tabs.

Really wish GitHub had a "show invisibles" option.

**Comment by exaskye** [comment]
image

Found [a userscript](https://greasyfork.org/en/scripts/32986-render-whitespace-on-github) to do just that.

**Comment by SFort** [comment]
Ye sorry about that for some reason IDEA didn't wan't to compile the latest commit so i did the feature on a older build n copied it over.

**Pull request merged**
