### PR TITLE
Toggle sprint

### PR DESCRIPTION
**Pull request by SFort**
~~#139 / /unascribed/Fabrication-Features/issues/34~~
mostly copied code from toggle_stance feature
Seemed wierd to be able to have 2 toggle keys so now the fabrication key inverts the accessibility setting

### CODE REVIEW

**Comment by exaskye** [comment]
I believe the original feature request refers to a toggle to *disable* sprinting.

**Comment by SFort** [comment]
i guess it would be pretty easy to add that on

**Comment by SFort** [comment]
do i open a seperate request?
and just to not mistake the intention again, should this be a keybind or just a normal fabrication feature?

**Comment by exaskye** [comment]
I interpreted the request as just a WOINA feature like no_experience that blanket-disables sprinting.

**Comment by exaskye** [comment]
May as well have this too.

**Pull request merged**
