### PR TITLE
expand taggable_players again

### PR DESCRIPTION
**Pull request by SFort**
allows inverting tags
adds `living_entity` and `server_player_entity` scriptable as valid options
revert nbt to caps for compat

### CODE REVIEW

**Comment by exaskye** [comment]
The numeric stuff in here is confusing and needs revision. I'm unable to think of good names for them, which is probably a sign they need to be thought more about...

**Comment by SFort** [comment]
[FeatureTaggablePlayers#72](https://github.com/unascribed/Fabrication/pull/423/files#diff-19a13e674bd8a101f6c2e42481fe5c02cd487b0cedc0044e794e545cf914a102R72)

mostly done since then a mask can be easily applied to the configs (bit0 - invert, bit1- keep behaviour for other entities)

but ye could probably be done better, dunno how tho

**Comment by exaskye** [comment]
I mean, it can still be an int internally, I just think exposing this to the user is really bad. I can't even really tell what these are *for*.

**Comment by SFort** [comment]
since features which accept Predicate\<LivingEntity\> are now valid the user should decide if the predicate should return true or false for non player entities

**Comment by exaskye** [comment]
So something like:

* tagged_players_only
* untagged_players_only
* tagged_players
* untagged_players

This still doesn't feel sufficiently clear, but it's better than 0 1 2 3.

**Pull request merged**
